from typing import Dict, List, TypedDict

from pydantic import BaseModel, Field


class AgentState(TypedDict):
    """
    Pydantic state model for the SQL QA agent.

    Attributes:
        user_query (str): The natural language query from the user.
        intent (Dict): The structured intent derived from the user query.
        query_plan (Dict): The plan for querying the database.
        generated_sql (str): The SQL query generated by the LLM.
        sql_error (str): The error message if SQL execution fails.
        query_result (List): The result of the SQL query execution.
        final_answer (str): The final natural language answer for the user.
        retry_count (int): The number of times the agent has retried a failed step.
    """

    user_query: str
    intent: Dict
    query_plan: Dict
    generated_sql: str
    sql_error: str
    query_result: List
    final_answer: str
    retry_count: int

