import logging
from typing import Dict, Any

from src.agents.doc_agent.agent import DocAgent
from src.llm_config import get_llm

logger = logging.getLogger(__name__)

# Global cache for the agent to avoid re-initializing on every call
_DOC_AGENT = None

def _get_doc_agent():
    """
    Helper to get or initialize the DocAgent.
    """
    global _DOC_AGENT
    if _DOC_AGENT is None:
        llm = get_llm()
        _DOC_AGENT = DocAgent(llm)
    return _DOC_AGENT

def doc_qa_tool(user_query: str) -> dict:
    """
    Use this tool to answer user questions based on internal documents.
    Input should be a natural language question.
    
    Returns a structured JSON-serializable response containing:
    - answer (str): Final natural language response generated by the agent.
    - data (list): Always empty for Doc QA.
    - sql (None): Not applicable.
    - error (str | None): Error message if processing failed.
    - status (str): “success” or “error”.
    - metadata (dict): Contains the source document name.
    """
    try:
        agent = _get_doc_agent()
        return agent.run(user_query)
        
    except Exception as e:
        logger.error(f"Doc QA Tool execution failed: {str(e)}")
        return {
            "answer": f"Sorry, an error occurred: {str(e)}",
            "data": [],
            "sql": None,
            "error": str(e),
            "status": "error",
            "metadata": {
                "source": None
            }
        }
