import os
import json
import logging
from datetime import datetime, date
from typing import Dict, Any, Optional, List
from dotenv import load_dotenv

from src.graph import create_graph
from src.logging_config import setup_logging

# Initialize logging to ensure it works even when imported as a standalone tool
setup_logging()
logger = logging.getLogger(__name__)

# Global cache for the compiled graph app to avoid re-compiling on every call
_GRAPH_APP = None

def _json_serializable(obj):
    """
    Recursively converts objects to JSON-serializable formats (e.g., Timestamps to strings).
    This ensures that ToolNode and orchestrator nodes can reliably JSON-serialize tool results.
    """
    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    if isinstance(obj, list):
        return [_json_serializable(item) for item in obj]
    if isinstance(obj, dict):
        return {k: _json_serializable(v) for k, v in obj.items()}
    if hasattr(obj, 'isoformat'): # Handle pandas/duckdb Timestamps
        return obj.isoformat()
    return obj

def _get_llm():
    """
    Helper to initialize the LLM based on environment variables.
    """
    load_dotenv()
    env = os.getenv("ENV", "local")
    
    if env == "local":
        from langchain_openai import ChatOpenAI
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
             raise ValueError("OPENAI_API_KEY is not set in environment. Please set it or check your .env file.")
        return ChatOpenAI(model="gpt-4o", temperature=0)
    
    elif env == "azure":
        try:
            # We assume azure_llm.py is in the search path
            from azure_llm import AzureOpenAIModel
            return AzureOpenAIModel()
        except ImportError:
            raise ImportError("azure_llm.py not found. Ensure it is in the PYTHONPATH if ENV=azure.")
    
    else:
        raise ValueError(f"Unsupported ENV: {env}")

def _get_compiled_graph():
    """
    Helper to get or initialize the compiled LangGraph app.
    """
    global _GRAPH_APP
    if _GRAPH_APP is None:
        llm = _get_llm()
        _GRAPH_APP = create_graph(llm)
    return _GRAPH_APP

def sql_qa_tool(user_query: str) -> dict:
    """
    Callable tool wrapper for the SQL QA LangGraph agent. 
    This tool processes a natural language query by executing the underlying
    SQL QA LangGraph workflow (intent extraction → query planning → SQL generation →
    validation → execution → answer generation) on the database and returns a structured response.

    The output is intentionally formatted as a stable contract so that the
    orchestrator agent can reliably:
        •	Decide how to present results to the user
        •	Handle errors gracefully
        •	Combine outputs with other tools if needed
    
    This tool returns a structured JSON-serializable response containing:
    - answer (str): Final natural language response generated by the agent.
    - data (list): Result set returned from the database query.
    - sql (str): Final SQL query executed (after any retries or fixes).
    - error (str | None): Error message if SQL execution failed; otherwise None.
    - status (str): “success” if execution succeeded, else “error”.
    - metadata (dict):
    - intent (dict): Parsed intent from the user query.
    - query_plan (dict): Generated plan used to construct the SQL query.
    
    Use this tool when the user asks questions that require querying a database.

    Args:
        user_query (str): The natural language query from the user.
    """
    try:
        # 1. Invoke the existing LangGraph SQL QA agent
        app = _get_compiled_graph()
        
        # Initial state for invocation as defined in AgentState
        initial_state = {
            "user_query": user_query,
            "retry_count": 0
        }
        
        # Synchronous invocation
        # We do NOT modify the existing graph logic
        final_state = app.invoke(initial_state)
        
        # 2. Extract Required Fields from Agent State
        sql_error = final_state.get("sql_error")
        query_plan = final_state.get("query_plan", {})
        plan_error = query_plan.get("error") if isinstance(query_plan, dict) else None
        
        # 3. Status Logic
        # The tool is successful only if there were no plan errors and no SQL execution errors.
        status = "success" if (sql_error is None and plan_error is None) else "error"
        
        # 4. Clean Data for JSON Serialization (Requirement for ToolNode and Orchestrator)
        # This converts Timestamps/dates to strings to prevent parsing errors downstream.
        raw_data = final_state.get("query_result", [])
        serializable_data = _json_serializable(raw_data)
        
        # 5. Construct Structured Tool Output
        return {
            "answer": final_state.get("final_answer", "No answer generated."),
            "data": serializable_data,
            "sql": final_state.get("generated_sql"),
            "error": sql_error or plan_error, # Return the first available error
            "status": status,
            "metadata": {
                "intent": final_state.get("intent"),
                "query_plan": query_plan
            }
        }
        
    except Exception as e:
        # 6. Error Handling: ensure the tool never crashes
        logger.error(f"SQL QA Tool execution failed: {str(e)}")
        return {
            "answer": f"Sorry, I encountered an internal error: {str(e)}",
            "data": [],
            "sql": None,
            "error": str(e),
            "status": "error",
            "metadata": {
                "intent": None,
                "query_plan": None
            }
        }

if __name__ == "__main__":
    # Example usage
    print("Example usage demonstrating the structured output:\n")
    try:
        # result = sql_qa_tool("Show total sales by region")
        pass
    except Exception as e:
        print(f"Could not run example: {e}")
