import os
import json
import logging
from typing import Dict, Any, Optional, List
from dotenv import load_dotenv

from src.graph import create_graph
from src.logging_config import setup_logging

# Initialize logging to ensure it works even when imported as a standalone tool
setup_logging()
logger = logging.getLogger(__name__)

# Global cache for the compiled graph app to avoid re-compiling on every call
_GRAPH_APP = None

def _get_llm():
    """
    Helper to initialize the LLM based on environment variables.
    """
    load_dotenv()
    env = os.getenv("ENV", "local")
    
    if env == "local":
        from langchain_openai import ChatOpenAI
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
             raise ValueError("OPENAI_API_KEY is not set in environment. Please set it or check your .env file.")
        return ChatOpenAI(model="gpt-4o", temperature=0)
    
    elif env == "azure":
        try:
            # We assume azure_llm.py is in the search path
            from azure_llm import AzureOpenAIModel
            return AzureOpenAIModel()
        except ImportError:
            raise ImportError("azure_llm.py not found. Ensure it is in the PYTHONPATH if ENV=azure.")
    
    else:
        raise ValueError(f"Unsupported ENV: {env}")

def _get_compiled_graph():
    """
    Helper to get or initialize the compiled LangGraph app.
    """
    global _GRAPH_APP
    if _GRAPH_APP is None:
        llm = _get_llm()
        _GRAPH_APP = create_graph(llm)
    return _GRAPH_APP

def sql_qa_tool(user_query: str) -> dict:
    """
    Callable tool wrapper for the SQL QA LangGraph agent. 
    This tool processes a natural language query by executing the underlying
    SQL QA LangGraph workflow (intent extraction → query planning → SQL generation →
    validation → execution → answer generation) on the database and returns a structured response.

    The output is intentionally formatted as a stable contract so that the
    orchestrator agent can reliably:
        •	Decide how to present results to the user
        •	Handle errors gracefully
        •	Combine outputs with other tools if needed
    
    Args:
        user_query (str): The natural language query from the user.
        
    Returns:
        dict: A structured response with the following fields:
        - answer (str): Final natural language response generated by the agent.
        - data (list): Result set returned from the database query.
        - sql (str): Final SQL query executed (after any retries or fixes).
        - error (str | None): Error message if SQL execution failed; otherwise None.
        - status (str): “success” if execution succeeded, else “error”.
        - metadata (dict):
        - intent (dict): Parsed intent from the user query.
        - query_plan (dict): Generated plan used to construct the SQL query.
    
    Intended Usage:
    - To be registered as a tool in a LangGraph-based orchestrator agent.
    - The orchestrator can route user queries to this tool when database-backed
    answers are required.
    """
    try:
        # 1. Invoke the existing LangGraph SQL QA agent
        app = _get_compiled_graph()
        
        # Initial state for invocation as defined in AgentState
        initial_state = {
            "user_query": user_query,
            "retry_count": 0
        }
        
        # Synchronous invocation
        # We do NOT modify the existing graph logic
        final_state = app.invoke(initial_state)
        
        # 2. Extract Required Fields from Agent State
        # Mapping requirements:
        # final_answer → answer
        # query_result → data
        # generated_sql → sql
        # sql_error → error
        # intent → metadata.intent
        # query_plan → metadata.query_plan
        
        sql_error = final_state.get("sql_error")
        query_plan = final_state.get("query_plan", {})
        plan_error = query_plan.get("error") if isinstance(query_plan, dict) else None
        
        # 3. Status Logic
        # The tool is successful only if there were no plan errors and no SQL execution errors.
        status = "success" if (sql_error is None and plan_error is None) else "error"
        
        # 4. Construct Structured Tool Output
        return {
            "answer": final_state.get("final_answer", "No answer generated."),
            "data": final_state.get("query_result", []),
            "sql": final_state.get("generated_sql"),
            "error": sql_error or plan_error, # Return the first available error
            "status": status,
            "metadata": {
                "intent": final_state.get("intent"),
                "query_plan": query_plan
            }
        }
        
    except Exception as e:
        # 5. Error Handling: ensure the tool never crashes
        logger.error(f"SQL QA Tool execution failed: {str(e)}")
        return {
            "answer": f"Sorry, I encountered an internal error: {str(e)}",
            "data": [],
            "sql": None,
            "error": str(e),
            "status": "error",
            "metadata": {
                "intent": None,
                "query_plan": None
            }
        }

if __name__ == "__main__":
    # Example usage as requested in the prompts
    # Mocking for demonstration if needed, but here it will try to run the real tool
    print("Example usage demonstrating the structured output:\n")
    try:
        # result = sql_qa_tool("Show total sales by region")
        # print(f"Answer: {result['answer']}")
        # print(f"Status: {result['status']}")
        # print(f"SQL: {result['sql']}")
        pass
    except Exception as e:
        print(f"Could not run example: {e}")
